name: Build

on:
  pull_request:
    branches: [ xbox ]
  push:
    branches: [ xbox ]

jobs:         
  #BUILD XBOX
  Xbox:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install and Setup Dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y flex bison clang lld llvm
        git clone https://github.com/XboxDev/nxdk.git --recursive

    - name: Compile
      run: |
        make -f Makefile.nxdk -j$(nproc) NXDK_DIR=$(pwd)/nxdk

    # Only create artifact on a push to master
    - if: github.event_name == 'push' 
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SDLPoPX_Xbox
        path: |
          doc
          bin/data
          bin/default.xbe
          bin/LICENSE.txt
          PrinceofPersia.iso
